source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec-expectations'
#  gem 'poltergeist', :git => 'https://github.com/Ajedi32/poltergeist.git', :branch => 'fix_windows_pgroup_error'
gem 'poltergeist'
gem 'selenium-webdriver'
gem 'launchy'
gem 'rest-client'
gem 'syntax'
gem 'activerecord'
gem 'activerecord-sqlserver-adapter'
gem 'tiny_tds'
gem 'luhn'
gem 'rake'